env:
  es6: true
  node: true
  mocha: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-console: off
  no-unused-vars: off
