env:
  es6: true
  node: true
  mocha: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-console: 0
  no-unused-vars: 0
